// <auto-generated />
using System;
using EmployeeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeeApi.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20260128013732_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeApi.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkingDays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = "DEL-12340-17MAY1994",
                            CreatedAt = new DateTime(2026, 1, 28, 1, 37, 32, 515, DateTimeKind.Utc).AddTicks(9140),
                            DailyRate = 2000.00m,
                            DateOfBirth = new DateTime(1994, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "JUAN",
                            LastName = "DELA CRUZ",
                            StartDate = new DateTime(2025, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2026, 1, 28, 1, 37, 32, 515, DateTimeKind.Utc).AddTicks(9142),
                            WorkingDays = "MWF"
                        },
                        new
                        {
                            Id = "SY*-00779-10SEP1994",
                            CreatedAt = new DateTime(2026, 1, 28, 1, 37, 32, 515, DateTimeKind.Utc).AddTicks(9146),
                            DailyRate = 1500.00m,
                            DateOfBirth = new DateTime(1994, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "ANNIE",
                            LastName = "SY",
                            MiddleName = "",
                            StartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2026, 1, 28, 1, 37, 32, 515, DateTimeKind.Utc).AddTicks(9147),
                            WorkingDays = "TTHS"
                        },
                        new
                        {
                            Id = "RAM-54321-23DEC1990",
                            CreatedAt = new DateTime(2026, 1, 28, 1, 37, 32, 515, DateTimeKind.Utc).AddTicks(9149),
                            DailyRate = 1800.00m,
                            DateOfBirth = new DateTime(1990, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "CARLOS",
                            LastName = "RAMOS",
                            MiddleName = "LOPEZ",
                            StartDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2026, 1, 28, 1, 37, 32, 515, DateTimeKind.Utc).AddTicks(9149),
                            WorkingDays = "MWF"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
